<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $title ?? 'FAITH AUTOMATION — Supplier Registry' }}</title>
    <style>
        @page {
            margin: 12mm 10mm 12mm 10mm;
            size: a4 landscape;
        }
        body {
            font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
            font-size: 9px;
            color: #1e293b;
            line-height: 1.3;
        }
        .header-table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 10px;
            border-bottom: 2px solid #0f172a;
            padding-bottom: 6px;
        }
        .header-table td {
            vertical-align: middle;
        }
        .brand-title {
            font-size: 15px;
            font-weight: bold;
            color: #0f172a;
            letter-spacing: 0.5px;
        }
        .report-subtitle {
            font-size: 11px;
            color: #2563eb;
            font-weight: 600;
            margin-top: 1px;
        }
        .meta-box {
            background-color: #f1f5f9;
            border: 1px solid #cbd5e1;
            border-radius: 4px;
            padding: 5px 8px;
            margin-bottom: 12px;
            font-size: 8.5px;
        }
        .meta-item {
            display: inline-block;
            margin-right: 15px;
        }
        .meta-label {
            font-weight: bold;
            color: #475569;
        }
        .meta-val {
            color: #0f172a;
        }
        .data-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 5px;
        }
        .data-table th, .data-table td {
            border: 1px solid #cbd5e1;
            padding: 5px 6px;
            text-align: left;
            font-size: 8.5px;
        }
        .data-table th {
            background-color: #0f172a;
            color: #ffffff;
            font-weight: bold;
            text-transform: uppercase;
            font-size: 8px;
            letter-spacing: 0.3px;
        }
        .data-table tr:nth-child(even) {
            background-color: #f8fafc;
        }
        .badge {
            display: inline-block;
            padding: 2px 5px;
            font-size: 7.5px;
            font-weight: bold;
            border-radius: 3px;
            text-align: center;
        }
        .badge-success { background-color: #10b981; color: #fff; }
        .badge-secondary { background-color: #64748b; color: #fff; }
        .badge-light { background-color: #f1f5f9; color: #0f172a; border: 1px solid #cbd5e1; }

        .footer-table {
            position: fixed;
            bottom: -8mm;
            left: 0;
            right: 0;
            width: 100%;
            border-top: 1px solid #e2e8f0;
            padding-top: 3px;
            font-size: 7.5px;
            color: #64748b;
        }
        .text-center { text-align: center; }
        .text-right { text-align: right; }
        .fw-bold { font-weight: bold; }
    </style>
</head>
<body>
    <!-- Header Banner -->
    <table class="header-table">
        <tr>
            <td>
                <div class="brand-title">FAITH AUTOMATION — Industrial Spare Parts Tracking System</div>
                <div class="report-subtitle">Supplier Management Registry &bull; Verified Vendor Directory</div>
            </td>
            <td class="text-right">
                <div style="font-size: 8px; color: #64748b;">
                    <strong>Generated:</strong> {{ $generated_at }}<br>
                    <strong>Generated By:</strong> {{ $generated_by }}
                </div>
            </td>
        </tr>
    </table>

    <!-- Meta Information Box -->
    <div class="meta-box">
        <div class="meta-item">
            <span class="meta-label">Total Suppliers:</span>
            <span class="meta-val fw-bold">{{ count($rows) }} Registered</span>
        </div>
        <div class="meta-item">
            <span class="meta-label">Active Suppliers:</span>
            <span class="meta-val fw-bold" style="color: #10b981;">{{ $active_count ?? count($rows) }}</span>
        </div>
        <div class="meta-item">
            <span class="meta-label">Export Scope:</span>
            <span class="meta-val">All Component Suppliers</span>
        </div>
    </div>

    <!-- Data Table -->
    <table class="data-table">
        <thead>
            <tr>
                <th style="width: 10%; text-align: center;">Code</th>
                <th style="width: 25%;">Supplier Name</th>
                <th style="width: 18%;">Contact Person</th>
                <th style="width: 14%;">Phone</th>
                <th style="width: 20%;">Email</th>
                <th style="width: 8%; text-align: center;">Status</th>
            </tr>
        </thead>
        <tbody>
            @forelse($rows as $row)
                <tr>
                    <td class="text-center fw-bold"><span class="badge badge-light">{{ $row['code'] }}</span></td>
                    <td class="fw-bold" style="color: #0f172a;">{{ $row['name'] }}</td>
                    <td>{{ $row['contact_person'] ?? '—' }}</td>
                    <td>{{ $row['phone'] ?? '—' }}</td>
                    <td>{{ $row['email'] ?? '—' }}</td>
                    <td class="text-center">
                        <span class="badge {{ $row['is_active'] ? 'badge-success' : 'badge-secondary' }}">
                            {{ $row['is_active'] ? 'Active' : 'Inactive' }}
                        </span>
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="6" class="text-center" style="padding: 15px; color: #64748b;">No supplier records found.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <!-- Footer -->
    <table class="footer-table">
        <tr>
            <td>FAITH AUTOMATION &bull; SpareTrack Manufacturing Execution System</td>
            <td class="text-right">Confidential &bull; Supplier Directory Export</td>
        </tr>
    </table>
</body>
</html>
