<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $title ?? 'FAITH AUTOMATION — Report' }}</title>
    <style>
        @page {
            margin: 15mm 12mm 15mm 12mm;
            size: a4 landscape;
        }
        body {
            font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
            font-size: 10px;
            color: #1e293b;
            line-height: 1.3;
        }
        .header-table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 12px;
            border-bottom: 2px solid #0f172a;
            padding-bottom: 8px;
        }
        .header-table td {
            vertical-align: middle;
        }
        .brand-title {
            font-size: 16px;
            font-weight: bold;
            color: #0f172a;
            letter-spacing: 0.5px;
        }
        .report-subtitle {
            font-size: 12px;
            color: #2563eb;
            font-weight: 600;
            margin-top: 2px;
        }
        .meta-box {
            background-color: #f1f5f9;
            border: 1px solid #cbd5e1;
            border-radius: 4px;
            padding: 6px 10px;
            margin-bottom: 12px;
            font-size: 9px;
        }
        .meta-item {
            display: inline-block;
            margin-right: 15px;
        }
        .meta-label {
            font-weight: bold;
            color: #475569;
        }
        .meta-val {
            color: #0f172a;
        }
        .data-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 5px;
        }
        .data-table th, .data-table td {
            border: 1px solid #cbd5e1;
            padding: 5px 6px;
            text-align: left;
            font-size: 9px;
        }
        .data-table th {
            background-color: #0f172a;
            color: #ffffff;
            font-weight: bold;
            text-transform: uppercase;
            font-size: 8.5px;
            letter-spacing: 0.3px;
        }
        .data-table tr:nth-child(even) {
            background-color: #f8fafc;
        }
        .badge {
            display: inline-block;
            padding: 2px 5px;
            font-size: 8px;
            font-weight: bold;
            border-radius: 3px;
            text-align: center;
        }
        .badge-primary { background-color: #2563eb; color: #fff; }
        .badge-success { background-color: #10b981; color: #fff; }
        .badge-danger  { background-color: #ef4444; color: #fff; }
        .badge-warning { background-color: #f59e0b; color: #fff; }
        .badge-secondary { background-color: #64748b; color: #fff; }
        .badge-purple  { background-color: #8b5cf6; color: #fff; }
        .badge-teal    { background-color: #0d9488; color: #fff; }

        .footer-table {
            position: fixed;
            bottom: -10mm;
            left: 0;
            right: 0;
            width: 100%;
            border-top: 1px solid #e2e8f0;
            padding-top: 4px;
            font-size: 8px;
            color: #64748b;
        }
        .text-center { text-align: center; }
        .text-right { text-align: right; }
        .fw-bold { font-weight: bold; }
    </style>
</head>
<body>
    <!-- Header Banner -->
    <table class="header-table">
        <tr>
            <td>
                <div class="brand-title">FAITH AUTOMATION</div>
                <div class="report-subtitle">{{ $title }}</div>
            </td>
            <td class="text-right">
                <div style="font-size: 9px; color: #64748b;">
                    <strong>Generated:</strong> {{ $generated_at }}<br>
                    <strong>Generated By:</strong> {{ $generated_by }}
                </div>
            </td>
        </tr>
    </table>

    <!-- Active Filters & Date Range Meta Box -->
    <div class="meta-box">
        <div class="meta-item">
            <span class="meta-label">Date Range:</span>
            <span class="meta-val">{{ $date_range }}</span>
        </div>
        <div class="meta-item">
            <span class="meta-label">Active Filters:</span>
            <span class="meta-val">{{ $active_filters }}</span>
        </div>
        <div class="meta-item">
            <span class="meta-label">Total Records:</span>
            <span class="meta-val">{{ count($rows) }}</span>
        </div>
    </div>

    <!-- Data Table -->
    <table class="data-table">
        <thead>
            <tr>
                @foreach($columns as $col)
                    <th style="{{ isset($col['width']) ? 'width: ' . $col['width'] . ';' : '' }}{{ isset($col['align']) ? 'text-align: ' . $col['align'] . ';' : '' }}">
                        {{ $col['label'] }}
                    </th>
                @endforeach
            </tr>
        </thead>
        <tbody>
            @forelse($rows as $row)
                <tr>
                    @foreach($columns as $col)
                        @php
                            $val = $row[$col['key']] ?? '-';
                            $align = $col['align'] ?? 'left';
                        @endphp
                        <td style="text-align: {{ $align }};">
                            @if(isset($col['badge']) && $col['badge'])
                                <span class="badge badge-{{ $row[$col['badge_color_key'] ?? 'color'] ?? 'primary' }}">
                                    {{ $val }}
                                </span>
                            @else
                                {{ $val }}
                            @endif
                        </td>
                    @endforeach
                </tr>
            @empty
                <tr>
                    <td colspan="{{ count($columns) }}" class="text-center" style="padding: 15px; color: #94a3b8;">
                        No records match the selected date range and filters.
                    </td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <!-- Footer -->
    <table class="footer-table">
        <tr>
            <td>FAITH AUTOMATION — Industrial Spare Parts Tracking System</td>
            <td class="text-right">Confidential Internal Manufacturing Document</td>
        </tr>
    </table>
</body>
</html>
